# -*- coding: utf-8 -*-
"""fin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o90d59GcJJZ0IDpzq-vtZ9f-_2yV8eWm
"""

# 🔧 FIX: Convert df_company.index.year to numpy array to avoid multidimensional indexing error in Streamlit
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
file_path = r"C:\Users\gupta\Downloads\Financial Statements.csv"
df = pd.read_csv(file_path)
df.columns = df.columns.str.strip()
df['Year'] = pd.to_datetime(df['Year'], format='%Y')

# App header
st.title("📊 Financial Dashboard: Multi-Company Forecast & KPI Insights")
st.markdown("Select a company from the dropdown to view performance, KPIs, and cash flow analysis.")

# Company selection
company_options = df['Company'].unique()
selected_company = st.selectbox("Choose a Company:", sorted(company_options))

df_company = df[df['Company'] == selected_company].copy()
df_company.set_index('Year', inplace=True)

df_company['EBITDA Margin (%)'] = (df_company['EBITDA'] / df_company['Revenue']) * 100
df_company['FCF/share YoY Growth (%)'] = df_company['Free Cash Flow per Share'].pct_change() * 100

# Fix year extraction for plots
years = df_company.index.year.values

# Revenue & Net Income
st.header(f"{selected_company} - Revenue & Net Income Over Time")
fig1, ax1 = plt.subplots(figsize=(10, 5))
ax1.plot(years, df_company['Revenue'].values, label='Revenue', marker='o')
ax1.plot(years, df_company['Net Income'].values, label='Net Income', marker='o')
ax1.set_xlabel("Year")
ax1.set_ylabel("(in millions)")
ax1.set_title(f"{selected_company} - Financial Performance")
ax1.legend()
st.pyplot(fig1)

# EBITDA Margin
st.header("EBITDA Margin")
fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(years, df_company['EBITDA Margin (%)'].values, label='EBITDA Margin (%)', marker='o', color='teal')
ax2.set_ylabel("EBITDA Margin (%)")
ax2.set_xlabel("Year")
ax2.legend()
st.pyplot(fig2)

# FCF/share Growth
st.header("Free Cash Flow/share Growth")
fig3, ax3 = plt.subplots(figsize=(10, 4))
ax3.plot(years, df_company['FCF/share YoY Growth (%)'].values, label='FCF/share Growth (%)', marker='o', color='darkorange')
ax3.set_ylabel("Growth (%)")
ax3.set_xlabel("Year")
ax3.legend()
st.pyplot(fig3)

# Cash Flow Breakdown
st.header("Cash Flow Health")
fig4, ax4 = plt.subplots(figsize=(10, 6))
ax4.plot(years, df_company['Cash Flow from Operating'].values, label='Operating CF', marker='o')
ax4.plot(years, df_company['Cash Flow from Investing'].values, label='Investing CF', marker='o')
ax4.plot(years, df_company['Cash Flow from Financial Activities'].values, label='Financing CF', marker='o')
ax4.set_title("Cash Flow Breakdown")
ax4.set_xlabel("Year")
ax4.set_ylabel("Cash Flow (in millions)")
ax4.legend()
st.pyplot(fig4)